# ==============================================================================
# Nightmare of Decay Profile
# ==============================================================================

extends = "base_wine_dxvk"

[meta]
id = "nightmare_of_decay"
name = "Nightmare of Decay"
version = "1.0"
icon = "applications-games"
developer = "Checkmaty"
genre = "Horror / FPS"
description = "PS1-styled survival horror FPS inspired by classic Resident Evil - scavenge, survive and escape a house of nightmares."

[paths]
game_dir = "/mnt/zram1/Nightmare.of.Decay-jc141"
dwarfs_image = "files/game-root.dwarfs"
dwarfs_mount = "files/.game-root-mnt"
overlay_dir = "files/game-root"
overlay_storage = "files/overlay-storage"
overlay_work = "files/.game-root-work"
executable = "steamclient_loader_x64.exe"
arguments = []

[runtime]
type = "wine"

[runtime.wine]
prefix_dir = "files/wine-prefix-ew"
arch = "win64"
sync_mode = "fsync"
dxvk = true
vkd3d = true
dll_overrides = { "winemenubuilder.exe" = "d", "mshtml" = "d", "d3d9" = "n", "dxgi" = "n", "d3d11" = "n", "d3d12" = "n" }

[graphics]
gpu = "discrete"
wayland_native = true

[performance]
gamemode = true
fps_limit = 60
